apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: store-admin
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: store-admin
  progressDeadlineSeconds: 60
  service:
    port: 80
    targetPort: 8081
    portDiscovery: true
    hosts:
      - "manage.aks.rocks"
    gateways:
      - aks-store-demo-external
  analysis:
    interval: 1m
    threshold: 10
    maxWeight: 20
    stepWeight: 10
    metrics:
      - name: request-success-rate
        thresholdRange:
          min: 99
        interval: 1m
      - name: request-duration
        thresholdRange:
          max: 500
        interval: 30s
      - name: error-rate
        thresholdRange:
          max: 10
        interval: 30s
    webhooks:
      - name: acceptance-test
        type: pre-rollout
        url: http://flagger-loadtester.dev/
        timeout: 60s
        metadata:
          type: bash
          cmd: "curl -s http://store-admin-canary.dev"
      - name: load-test
        url: http://flagger-loadtester.dev/
        timeout: 5s
        metadata:
          cmd: "hey -z 1m -q 10 -c 2 http://store-admin-canary.dev"