---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: aks-store-demo
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: istio
  secretRef:
    name: aks-store-demo
  url: https://github.com/pauldotyu/aks-store-demo-manifests
