---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flagger
  namespace: flux-system
spec:
  chart:
    spec:
      chart: flagger
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: flagger
  install:
    crds: Create
    createNamespace: true
  interval: 1m0s
  targetNamespace: flagger-system
  upgrade:
    crds: CreateReplace
  values:
    meshProvider: istio
    prometheus:
      install: true
