apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ingressgateway.yaml
- ../../base
namespace: dev
images:
- name: ghcr.io/pauldotyu/aks-store-demo/store-front
  newName: ghcr.io/pauldotyu/aks-store-demo/store-front # {"$imagepolicy": "flux-system:store-front:name"}
  newTag: 1.0.0 # {"$imagepolicy": "flux-system:store-front:tag"}
patches:
- patch: |-
    apiVersion: v1
    kind: Service
    metadata:
      name: store-front
    $patch: delete
