---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: flagger-loadtester
  namespace: flux-system
spec:
  interval: 1m0s
  provider: generic
  ref:
    semver: 1.x
  url: oci://ghcr.io/fluxcd/flagger-manifests
